title: Palindrom Standards
description: Composable coding standards and guidelines
baseurl: /standards
url: https://palindrom-ai.github.io
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-include-cache

# Aux links for the upper right navigation
aux_links:
  "GitHub":
    - "https://github.com/palindrom-ai/standards"

# Footer content
footer_content: "Palindrom Standards"

# Color scheme
color_scheme: dark

# Search
search_enabled: true
search:
  heading_level: 2
  previews: 3

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"
